### ISSUE TITLE
doze support

### ISSUE THREAD

**Issue by rdp** [ph7/xray#1]
> > require 'xray'
> > ArgumentError: unsupported signal SIGQUIT
> >         from c:/ruby18/lib/ruby/gems/1.8/gems/xray-1.1/lib/xray/thread_dump_signal_handler.rb:6:in `trap'
> >         from c:/ruby18/lib/ruby/gems/1.8/gems/xray-1.1/lib/xray/thread_dump_signal_handler.rb:6

**Comment by ph7** [comment]
Seems like you are running on Windows. Windows is not supported by the XRay gem (Windows differs too much from UNIX semantics and is generally considered not to be the best platform to deploy Ruby applications ;-)
